spring:
  datasource:
    url: jdbc:postgresql://ec2-13-229-91-43.ap-southeast-1.compute.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
